app_img_index:
    path:     /layout/{name}/{x}/{y}/{z}/{gridX}/{gridY}.png
    defaults: { _controller: "AppMapBundle:Image:layout" }

app_grid_index:
    path:     /grid/{name}/{x}/{y}/
    defaults: { _controller: "AppMapBundle:Image:grid" }

app_map_save_map:
    path:     /{id}/save_map/{source}
    defaults: { _controller: "AppMapBundle:Image:saveMap" }
    requirements:
        id:  \d+

app_map_save_coords:
    path:     /{id}/save_coord
    defaults: { _controller: "AppMapBundle:Image:saveCoord" }
    requirements:
        id:  \d+