app_map_index:
    path:     /
    defaults: { _controller: "AppMapBundle:Map:index" }

app_map_show:
    path:     /{id}/edit
    defaults: { _controller: "AppMapBundle:Map:show" }
    requirements:
        id:  \d+

app_map_kp_map:
    path:     /{id}/getCoords
    defaults: { _controller: "AppMapBundle:Map:getCoordinates" }
    requirements:
        id:  \d+

app_map_new:
    path:     /new
    defaults: { _controller: "AppMapBundle:Map:new" }


app_map_save:
    path:     /{id}/save
    defaults: { _controller: "AppMapBundle:Map:save" }
    requirements: { _method: post }

app_map_view:
    path:     /{id}/view
    defaults: { _controller: "AppMapBundle:Map:view" }
    requirements:
        id:  \d+

app_map_create:
    path:     /create/
    defaults: { _controller: "AppMapBundle:Map:create" }
    requirements: { _method: post }

app_map_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppMapBundle:Map:delete" }
    requirements:
        id:  \d+
