app_map_show:
    path:     /{id}/show/{type}
    defaults: { _controller: "AppMapBundle:Map:show" }
    requirements:
        id:  \d+

app_map_new:
    path:     /{id}/new
    defaults: { _controller: "AppMapBundle:Map:new" }
    requirements:
        id:  \d+


app_map_save:
    path:     /{id}/save
    defaults: { _controller: "AppMapBundle:Map:save" }
    requirements: { _method: post }


app_map_save_map:
    path:     /{id}/save_map
    defaults: { _controller: "AppMapBundle:Map:saveMap" }
    requirements:
        id:  \d+


app_map_save_coords:
    path:     /{id}/save_coord
    defaults: { _controller: "AppMapBundle:Map:saveCoord" }
    requirements:
        id:  \d+

app_map_view:
    path:     /{id}/view
    defaults: { _controller: "AppMapBundle:Map:view" }
    requirements:
        id:  \d+

app_map_create:
    path:     /create/
    defaults: { _controller: "AppMapBundle:Map:create" }
    requirements: { _method: post }

app_map_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppMapBundle:Map:delete" }
    requirements:
        id:  \d+
