<?php

namespace App\MapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoordinatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesRepository extends EntityRepository
{
}
