App\MapBundle\Entity\Map:
    type: entity
    repositoryClass: App\MapBundle\Repository\MapRepository
    table: map
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        img:
            type: text
        x:
            type: smallint
            length: 2
            options:
                default: 0
        y:
            type: smallint
            length: 2
            options:
                default: 0
        radius:
            type: smallint
            length: 2
            options:
                default: 10
    oneToMany:
        coords_m:
            targetEntity: Coordinates
            mappedBy: coords