App\MapBundle\Entity\Task:
    type: entity
    repositoryClass: App\MapBundle\Repository\TaskRepository
    table: task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        tasks:
            targetEntity: Map
            mappedBy: maps